version: '3.3'

networks:
  aw-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - aw-network
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - aw-network
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
#      - STORAGE_TYPE=mysql
#      - MYSQL_HOST=mysql
#      # Uncomment to enable scribe
#      # - SCRIBE_ENABLED=true
      - SELF_TRACING_ENABLED=true
#       Uncomment to enable debug logging
      - JAVA_OPTS=-Dlogging.level.zipkin2=DEBUG
    ports:
      - 9411:9411
      # Uncomment if you set SCRIBE_ENABLED=true
#    depends_on:
#      - storage
